# Generated by Django 3.0.8 on 2020-08-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='liking',
        ),
    ]
